name: MLDL

channels:
  - pytorch

dependencies:
  - python=3.6
  - pip
  - pytorch
  - torchvision
  - cudatoolkit=10.2
  - pip:
      - pytest==5.3.5
      - jupyter
      - matplotlib==3.2.1
      - tensorboard==2.2.1